### ISSUE TITLE
Launch Day ToDo

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/Developer_Quiz_Site#1]
Hey all,

Just a quick list of things to do on launch day 🙂 

- [x] Transfer repository to freeCodeCamp org (will need Mrugesh to assist)
- [x] Make repository public
- [x] Figure out deployment approach (GitHub Pages, maybe?)
- [x] Set up DNS for developerquiz.org 
- [x] Update README to be project specific (remove CRA boilerplate)
- [x] Community Health files (code of conduct, contributing, license) - can copy from freeCodeCamp repo

**Comment by jdwilkin4** [comment]
Successful launch!
